// SPDX-FileCopyrightText: Copyright (c) 2025-2026 NVIDIA CORPORATION & AFFILIATES. All rights reserved.
// SPDX-License-Identifier: Apache-2.0

//! Host git identity + SSH-cert signing config for a sandbox.
//!
//! PassportControl / YubiKey setups sign with an **SSH certificate in the
//! agent**, not a `user.signingKey` file. The sandbox therefore gets:
//! `gpg.format=ssh`, `commit.gpgsign=true`, and
//! `gpg.ssh.defaultKeyCommand=ssh-add -L` so git asks the forwarded agent.
//! `allowedSignersFile` is copied and rewritten to a `/tmp` path because the
//! host path (`~/Library/Group Containers/...`) does not exist in-pod.

use std::collections::HashMap;
use std::fmt::Write as _;

/// Writable Landlock path for the materialized git config.
pub const SANDBOX_GIT_DIR: &str = "/tmp/openshell-git";
/// `GIT_CONFIG_GLOBAL` inside the sandbox. Home is often read-only.
pub const SANDBOX_GIT_CONFIG: &str = "/tmp/openshell-git/config";
/// Rewritten `gpg.ssh.allowedSignersFile`.
pub const SANDBOX_GIT_ALLOWED_SIGNERS: &str = "/tmp/openshell-git/allowed_signers";
/// Portable command: list certs/keys from the forwarded agent.
pub const DEFAULT_KEY_COMMAND: &str = "ssh-add -L";

/// Host-observed signing-related git settings. No private key material.
#[derive(Debug, Clone, Default, PartialEq, Eq)]
pub struct HostGitSignConfig {
    pub name: Option<String>,
    pub email: Option<String>,
    pub gpg_format: Option<String>,
    pub commit_gpgsign: bool,
    pub tag_gpgsign: bool,
    /// Host filesystem path; rewritten on render.
    pub allowed_signers_host_path: Option<String>,
}

impl HostGitSignConfig {
    /// True when the host is doing SSH-format commit signing (certs or keys).
    #[must_use]
    pub fn is_ssh_signing(&self) -> bool {
        self.commit_gpgsign
            || self
                .gpg_format
                .as_deref()
                .is_some_and(|fmt| fmt.eq_ignore_ascii_case("ssh"))
    }
}

/// Point sandbox git at the pinned global config and ignore image `/etc/gitconfig`.
pub fn inject_git_sign_env(env: &mut HashMap<String, String>) {
    env.insert("GIT_CONFIG_GLOBAL".to_string(), SANDBOX_GIT_CONFIG.to_string());
    env.insert("GIT_CONFIG_NOSYSTEM".to_string(), "1".to_string());
}

/// Quote a git-config value (needed for emails and similar).
#[must_use]
pub fn git_config_quote(value: &str) -> String {
    if value
        .chars()
        .any(|c| c.is_whitespace() || matches!(c, '"' | '\\' | '#' | ';'))
    {
        let escaped = value.replace('\\', "\\\\").replace('"', "\\\"");
        format!("\"{escaped}\"")
    } else {
        value.to_string()
    }
}

/// Render a sandbox-only gitconfig. Never writes `user.signingKey` — SSH
/// certs live in the agent and are selected via `defaultKeyCommand`.
#[must_use]
pub fn render_sandbox_gitconfig(cfg: &HostGitSignConfig, include_allowed_signers: bool) -> String {
    let mut out = String::from("# generated by openshell --forward-agent (SSH cert / agent signing)\n");
    let mut user_section = String::new();
    if let Some(name) = cfg.name.as_deref().filter(|s| !s.is_empty()) {
        let _ = writeln!(user_section, "\tname = {}", git_config_quote(name));
    }
    if let Some(email) = cfg.email.as_deref().filter(|s| !s.is_empty()) {
        let _ = writeln!(user_section, "\temail = {}", git_config_quote(email));
    }
    if !user_section.is_empty() {
        out.push_str("[user]\n");
        out.push_str(&user_section);
    }

    if cfg.is_ssh_signing() {
        out.push_str("[gpg]\n\tformat = ssh\n");
        if cfg.commit_gpgsign {
            out.push_str("[commit]\n\tgpgsign = true\n");
        }
        if cfg.tag_gpgsign {
            out.push_str("[tag]\n\tgpgsign = true\n");
        }
        out.push_str("[gpg \"ssh\"]\n");
        let _ = writeln!(
            out,
            "\tdefaultKeyCommand = {}",
            git_config_quote(DEFAULT_KEY_COMMAND)
        );
        if include_allowed_signers {
            let _ = writeln!(
                out,
                "\tallowedSignersFile = {}",
                git_config_quote(SANDBOX_GIT_ALLOWED_SIGNERS)
            );
        }
    }
    out
}

#[cfg(test)]
mod tests {
    use super::*;

    #[test]
    fn render_cert_signing_has_no_signing_key() {
        let cfg = HostGitSignConfig {
            name: Some("Harry Anderson".into()),
            email: Some("harry@example.com".into()),
            gpg_format: Some("ssh".into()),
            commit_gpgsign: true,
            tag_gpgsign: false,
            allowed_signers_host_path: Some("/Users/harry/Library/Group Containers/x/allowed_signers".into()),
        };
        let rendered = render_sandbox_gitconfig(&cfg, true);
        assert!(!rendered.to_ascii_lowercase().contains("signingkey"));
        assert!(rendered.contains("format = ssh"));
        assert!(rendered.contains("gpgsign = true"));
        assert!(rendered.contains("defaultKeyCommand = \"ssh-add -L\""));
        assert!(rendered.contains(SANDBOX_GIT_ALLOWED_SIGNERS));
        assert!(!rendered.contains("/Users/harry"));
        assert!(rendered.contains("name = \"Harry Anderson\""));
    }

    #[test]
    fn render_omits_allowed_signers_when_host_file_missing() {
        let cfg = HostGitSignConfig {
            gpg_format: Some("ssh".into()),
            commit_gpgsign: true,
            ..HostGitSignConfig::default()
        };
        let rendered = render_sandbox_gitconfig(&cfg, false);
        assert!(!rendered.contains("allowedSignersFile"));
        assert!(rendered.contains("defaultKeyCommand = \"ssh-add -L\""));
    }

    #[test]
    fn ssh_signing_detected_from_gpgsign_alone() {
        let cfg = HostGitSignConfig {
            commit_gpgsign: true,
            ..HostGitSignConfig::default()
        };
        assert!(cfg.is_ssh_signing());
    }
}
